//Shading Model: Metallic
Raysample[SampleIndex].Color = Payload.BaseColor + (Payload.Radiance * 50.0f);
Raysample[SampleIndex].Metallic = 1;
Raysample[SampleIndex].Roughness = 1;
Raysample[SampleIndex].ShadingModel = Payload.ShadingModelID;
Raysample[SampleIndex].BlendingMode = Payload.BlendingMode;

#include "AQ_ShadingModel_Metallic_Lighting.ush"
#include "AQ_ShadingModel_MetallicMirror_LightingPoint.ush"

break;